name: build-cachelib-ubuntu
on:
  schedule:
    - cron:  '30 5 * * 0,3'
jobs:
  build-cachelib-ubuntu:
    name: "Ubuntu/Latest - Build CacheLib with all dependencies"
    runs-on: self-hosted
    steps:
      - name: "update packages"
        run: sudo apt-get update
      - name: "install sudo,git"
        run: sudo apt-get install -y git procps
      - name: "System Information"
        run: |
          echo === uname ===
          uname -a
          echo === /etc/os-release ===
          cat /etc/os-release
          echo === df -hl ===
          df -hl
          echo === free -h ===
          free -h
          echo === top ===
          top -b -n1 -1 -Eg || timeout 1 top -b -n1
          echo === env ===
          env
          echo === cc -v ===
          cc -v
          echo === g++ -v ===
          g++ -v
      - name: "configure sudo to keep proxy environment variables"
        run: echo 'Defaults    env_keep += "HTTPS_PROXY https_proxy HTTP_PROXY http_proxy NO_PROXY no_proxy"' >> /etc/sudoers
      - name: "checkout sources"
        uses: actions/checkout@v2
      - name: "build CacheLib using build script"
        run: ./contrib/build.sh -j -v -T
